### ISSUE TITLE
[Feature Request] Rounded Corners

### ISSUE THREAD

**Issue by charmbyte** [hyprwm/hyprpaper#182]
Purely cosmetic and I'm not sure if this would be a hyprpaper thing or a Hyprland thing, or even if it's within the scope of what hyprpaper is meant for, but it would be cool to be able to have rounded corner wallpapers with some default background color. When I used Gnome, there was an extension that would do this and it was pretty neat. Certainly this is 100% my opinion, but it's something unique that I think actually does add a certain aesthetic that could mesh well with Hyprland.

**Comment by fufexan** [comment]
This wouldn't work well with bars for example. Since hyprpaper draws the wallpaper on the background layer and bars are usually on the bg/fg layers, hyprpaper doesn't care about exclusive areas (as set by bars), and would draw the rounded corners right under the bar.
A better idea is to have the rounded corners handled by the shell, as can be seen in [end-4's dots](https://github.com/end-4/dots-hyprland).

**Comment by vaxerski** [comment]
as above
