### ISSUE TITLE
[Feature request] Preload directory

### ISSUE THREAD

**Issue by ThatOneCalculator** [hyprwm/hyprpaper#4]
Would be great for those who apply a wallpaper randomly per workspace

**Comment by vaxerski** [comment]
generally a bad idea because it would incentivize people to do that, which is a bad idea. One wallpaper is around 8 - 20MB, and preloading it takes ~50-400ms. Now imagine someone just preloading his "wallpapers" folder with 100 wallpapers. He'll be waiting 10s for it to open, and will see a huge 1.5GB usage of RAM.

**Comment by ThatOneCalculator** [comment]
I already preload like half a gig of wallpapers kekw

**Comment by vaxerski** [comment]
you can make a simple script to print all the files in a format of `preload=path`, if you really want to, so idk why bother even

**Comment by Auxnon** [comment]
Well I figure I'll post my bash script for anyone else that finds this, this just uses a wildcard for my wallpapers directory.  Pardon my bashing I'think you can do this without a for using pipes and @ but I couldn't figure it out.

```bash
array=(~/Pictures/wallpapers/*)
for i in ${array[@]}; do
    hyprctl hyprpaper preload $i
done
```
