### ISSUE TITLE
Support for JPEG XL images

### ISSUE THREAD

**Issue by CIAvash** [hyprwm/hyprpaper#85]
[JPEG XL](https://jpeg.org/jpegxl/) and `.jxl` extension.

**Comment by Atemo-C** [comment]
This definitely would be nice. Today, I converted my wallpapers from already highly-optimized PNGs *(with `oxipng`)* to lossless `.jxl` with the `cjxl` tool like I did with other similar images on my system, saving over a GiB of space on my limited storage with the wallpapers alone. I then realized that none of my wallpapers can be used by Hyprpaper in this format, showing this "error" message.
```LOG
Not a JPEG file: starts with 0xff 0x0a
```

JPEG XL is, unfortunately, still not very popular, and it seems like there is little incentive to adopt it in the industry at large, so it is understandable if this is not a priority by any means. Still would be nice to have.

**Comment by Morxemplum** [comment]
> JPEG XL is, unfortunately, still not very popular, and it seems like there is little incentive to adopt it in the industry at large, so it is understandable if this is not a priority by any means. Still would be nice to have.

I strongly disagree. Prior to the Chromium team killing support, this format gained tons of support by industry partners, including but not limited to Intel, Meta (Facebook/Instagram), Shopify, and Adobe. And even after Chromium killed support, Apple added JPEG XL support in Safari, macOS, and iOS. Adobe supports JPEG XL in Photoshop and Camera RAW. Affinity Photo also supports the format.

JPEG XL is well covered by the FOSS ecosystem. Supported by programs such as Krita, GIMP, Darktable, ImageMagick, and FFmpeg. It has support in both Qt and GTK frameworks. If we look at desktop environments, GNOME and KDE Plasma both support setting JPEG XL as background images. Even COSMIC added JPEG XL support since the [third Alpha release](https://blog.system76.com/post/cosmic-alpha-3). 

The only reason why JPEG XL is "still not very popular" can purely be attributed to Chromium killing support for it. Since Chromium practically holds a monopoly in the web browser space, that has stunted JPEG XL from becoming the ubiquitous choice for a next-generation image format.

**Comment by Atemo-C** [comment]
@Morxemplum I agree with you, and unfortunately, who controls the web controls a lot of standards' adoption/use.

I am still waiting for whenever hyprpaper gets support for it (if I would know how to/have time to, I would create a PR to implement support for it), if it ever happens, because I really am a fan of it, and use it everywhere on my system but game art and, of course, wallpapers.

**Comment by arrufat** [comment]
Hi! I am also a big fan of JPEG-XL, I finally found the time to give Hyprland & Co a serious try. Luckily, I was familiar with libjxl, so we should have support for JXL soon, hopefully.

**Comment by Atemo-C** [comment]
Thank you for your work, @arrufat !

**Comment by vaxerski** [comment]
no need. I've made a new library https://github.com/hyprwm/hyprgraphics to which I'll offload image loading in the future for all hypr* apps, so we don't need to duplicate implementations
